/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phammemquanlybatdongsan;

import Modify.KetNoi;
import Data.KhachHang;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QuanLyKhachHang extends javax.swing.JInternalFrame {
    KetNoi ketnoi;
    int index;
    ArrayList<KhachHang> listKH = new ArrayList<>();
    /**
     * Creates new form KhachHangView
     */
    public QuanLyKhachHang() {
        initComponents();
        rdoNam_Khachhang.setSelected(true);
        btnSua_Khachhang.setEnabled(false);
        btnXoa_Khachhang.setEnabled(false);
       
            ketnoi = new KetNoi();
            ketnoi.ketnoi();
        
        try {
            filltotable();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnThem_Khachhang = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSua_Khachhang = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnXoa_Khachhang = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnMoi_KhachHang = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdoNam_Khachhang = new javax.swing.JRadioButton();
        rdoNu_Khachhang = new javax.swing.JRadioButton();
        txtHoTen_Khachhang = new javax.swing.JTextField();
        txtMa_Khachhang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoDT_Khachhang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCMND_Khachhang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail_Khachhang = new javax.swing.JTextField();
        txtNgaySinh_Khachhang = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Khachhang = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        btnThem_Khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnThem_Khachhang.setBorderPainted(false);
        btnThem_Khachhang.setContentAreaFilled(false);
        btnThem_Khachhang.setFocusable(false);
        btnThem_Khachhang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem_Khachhang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem_Khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_KhachhangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThem_Khachhang);
        jToolBar1.add(jSeparator1);

        btnSua_Khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua_Khachhang.setBorderPainted(false);
        btnSua_Khachhang.setContentAreaFilled(false);
        btnSua_Khachhang.setFocusable(false);
        btnSua_Khachhang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSua_Khachhang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSua_Khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_KhachhangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSua_Khachhang);
        jToolBar1.add(jSeparator2);

        btnXoa_Khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa_Khachhang.setBorderPainted(false);
        btnXoa_Khachhang.setContentAreaFilled(false);
        btnXoa_Khachhang.setFocusable(false);
        btnXoa_Khachhang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa_Khachhang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa_Khachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_KhachhangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnXoa_Khachhang);
        jToolBar1.add(jSeparator4);

        btnMoi_KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnMoi_KhachHang.setBorderPainted(false);
        btnMoi_KhachHang.setContentAreaFilled(false);
        btnMoi_KhachHang.setFocusable(false);
        btnMoi_KhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMoi_KhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMoi_KhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoi_KhachHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMoi_KhachHang);
        jToolBar1.add(jSeparator3);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator5);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Khách Hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Mã :");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Họ Tên :");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Ngày Sinh :");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Giới Tính :");

        buttonGroup1.add(rdoNam_Khachhang);
        rdoNam_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdoNam_Khachhang.setText("Nam");

        buttonGroup1.add(rdoNu_Khachhang);
        rdoNu_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rdoNu_Khachhang.setText("Nữ");

        txtHoTen_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtMa_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Số ĐT :");

        txtSoDT_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("CMND :");

        txtCMND_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Email :");

        txtEmail_Khachhang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMa_Khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtHoTen_Khachhang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgaySinh_Khachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCMND_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoDT_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)
                                .addComponent(txtEmail_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoNam_Khachhang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoNu_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCMND_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtEmail_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtSoDT_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(52, 52, 52)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtHoTen_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMa_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgaySinh_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoNu_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoNam_Khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tbl_Khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Họ Tên", "Ngày Sinh", "Giới Tính", "SĐT", "CMND", "Email"
            }
        ));
        tbl_Khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Khachhang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoa_KhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_KhachhangActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoa_KhachhangActionPerformed

    private void btnMoi_KhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoi_KhachHangActionPerformed
        // TODO add your handling code here:
        moi();
    }//GEN-LAST:event_btnMoi_KhachHangActionPerformed

    private void btnSua_KhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_KhachhangActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSua_KhachhangActionPerformed

    private void btnThem_KhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_KhachhangActionPerformed
        // TODO add your handling code here:
        them();
    }//GEN-LAST:event_btnThem_KhachhangActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbl_KhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhachhangMouseClicked
        // TODO add your handling code here:
        showDetail();    
    }//GEN-LAST:event_tbl_KhachhangMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi_KhachHang;
    private javax.swing.JButton btnSua_Khachhang;
    private javax.swing.JButton btnThem_Khachhang;
    private javax.swing.JButton btnXoa_Khachhang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton rdoNam_Khachhang;
    private javax.swing.JRadioButton rdoNu_Khachhang;
    private javax.swing.JTable tbl_Khachhang;
    private javax.swing.JTextField txtCMND_Khachhang;
    private javax.swing.JTextField txtEmail_Khachhang;
    private javax.swing.JTextField txtHoTen_Khachhang;
    private javax.swing.JTextField txtMa_Khachhang;
    private com.toedter.calendar.JDateChooser txtNgaySinh_Khachhang;
    private javax.swing.JTextField txtSoDT_Khachhang;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel myModel;
    public void filltotable() throws SQLException {
        myModel = (DefaultTableModel)tbl_Khachhang.getModel();
        myModel.setRowCount(0);
        String sql = "select * from KhachHang";
        Statement stt = ketnoi.con.createStatement();
        ResultSet rs = stt.executeQuery(sql);
        while(rs.next()) {
            String maKH = rs.getString("MaKH");
            String hoTen = rs.getString("TenKH");
            String ngaySinh = rs.getString("NgaySinhKH");
            String gioiTinh = rs.getString("GioiTinhKH");
            String SDT = rs.getString("SDTKH");
            String CMND = rs.getString("CMNDKH");
            String Email = rs.getString("EmailKH");
            myModel.addRow(new Object[]{maKH, hoTen, ngaySinh, gioiTinh, SDT, CMND, Email});
            listKH.add(new KhachHang(maKH, hoTen, ngaySinh, gioiTinh, SDT, CMND, Email));
        }
    }
    
    public boolean check() {
        if(txtMa_Khachhang.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Hãy điền mã khách hàng !");
            txtMa_Khachhang.requestFocus(true);
            return false;
        }
        for(KhachHang x : listKH) {
            if(txtMa_Khachhang.getText().equalsIgnoreCase(x.getMakh())){
                JOptionPane.showMessageDialog(this, "Mã khách hàng đã tồn tại");
                txtMa_Khachhang.requestFocus(true);
                return false;
            }
        }
        if(txtHoTen_Khachhang.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Hãy điền họ tên khách hàng !");
            txtHoTen_Khachhang.requestFocus(true);
            return false;
        }
        //Check Số điện thoại
        if(txtSoDT_Khachhang.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Hãy điền số điện thoại khách hàng !");
            txtSoDT_Khachhang.requestFocus(true);
            return false;
        }
        String sdtFormat = "0\\d{9}";
        if(!txtSoDT_Khachhang.getText().matches(sdtFormat)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại có 10 số và đúng định dạng 0[1->9]");
            txtSoDT_Khachhang.requestFocus(true);
            return false;
        }
        for(KhachHang x : listKH) {
            if(txtSoDT_Khachhang.getText().equalsIgnoreCase(x.getSodt())){
                JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại");
                txtSoDT_Khachhang.requestFocus(true);
                return false;
            }
        }
        if(txtCMND_Khachhang.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Hãy điền cmnd khách hàng !");
            txtCMND_Khachhang.requestFocus(true);
            return false;
        }
        String cmndFormat = "\\d{12}";
        if(!txtCMND_Khachhang.getText().matches(cmndFormat)) {
            JOptionPane.showMessageDialog(this, "CMND không hợp lệ !");
            txtCMND_Khachhang.requestFocus(true);
            return false;
        } 
        for(KhachHang x : listKH) {
            if(txtCMND_Khachhang.getText().equalsIgnoreCase(x.getCmnd())){
                JOptionPane.showMessageDialog(this, "CMND đã tồn tại");
                txtCMND_Khachhang.requestFocus(true);
                return false;
            }
        }
        if(txtEmail_Khachhang.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Hãy điền email khách hàng !");
            txtEmail_Khachhang.requestFocus(true);
            return false;
        }
        String emailFormat = "\\w+@gmail.com";
        if(!txtEmail_Khachhang.getText().matches(emailFormat)){
            JOptionPane.showMessageDialog(this, "Email không hợp lệ !");
            txtEmail_Khachhang.requestFocus(true);
            return false;
        }
        for(KhachHang x : listKH) {
             if(txtEmail_Khachhang.getText().equalsIgnoreCase(x.getEmail())){
                 JOptionPane.showMessageDialog(this, "Email đã tồn tại");
                 txtEmail_Khachhang.requestFocus(true);
                 return false;
             }
        }
        return true;
    }
    
    public void them() {
        if(check()) {
            String gt = null;
            if(rdoNam_Khachhang.isSelected()){
                gt = "Nam";
            }
            else{gt = "Nữ";}
            String maKH = txtMa_Khachhang.getText();
            String hoTen = txtHoTen_Khachhang.getText();
            String ngaySinh;
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                ngaySinh = sdf.format(txtNgaySinh_Khachhang.getDate());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Chọn lại ngày sinh");
                return;
            }
            String SDT = txtSoDT_Khachhang.getText();
            String CMND = txtCMND_Khachhang.getText();
            String Email = txtEmail_Khachhang.getText();
            try {
                String sql = "INSERT INTO KhachHang " +
                        "VALUES ('"+maKH.trim()+"',N'"+hoTen.trim()+"','"+ngaySinh.trim()+"',N'"+gt.trim()+"','"+SDT.trim()+"','"+CMND.trim()+"','"+Email.trim()+"')";
                Statement stt = ketnoi.con.createStatement();
                int rs = stt.executeUpdate(sql);
                listKH.add(new KhachHang(maKH, hoTen, ngaySinh, gt, SDT, CMND, Email));
                myModel.addRow(new Object[] {maKH, hoTen, ngaySinh, gt, SDT,CMND,Email}); 
                JOptionPane.showMessageDialog(this, "Thêm mới thành công");
                moi();
            } catch (HeadlessException | SQLException e) {
                System.out.println(e);
            }
            
        }
    }
    
    public void moi() {
        btnThem_Khachhang.setEnabled(true);
        btnSua_Khachhang.setEnabled(false);
        btnXoa_Khachhang.setEnabled(false);
        tbl_Khachhang.clearSelection();
        txtMa_Khachhang.setText("");
        txtHoTen_Khachhang.setText("");
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse("2020-01-10");
            txtNgaySinh_Khachhang.setDate(date);
        } catch (Exception e) {
        }
        rdoNam_Khachhang.setSelected(true);
        txtSoDT_Khachhang.setText("");
        txtEmail_Khachhang.setText("");
        txtCMND_Khachhang.setText("");
        txtMa_Khachhang.requestFocus(true);
        txtMa_Khachhang.setEditable(true);
    }
    
    public void xoa(){
        int chon = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa ?");
        if(chon == 0){
            int i = tbl_Khachhang.getSelectedRow();
            try {
                String sql = "Delete KhachHang " +
                    "Where MaKH = '"+txtMa_Khachhang.getText().trim()+"'";
            Statement stt = ketnoi.con.createStatement();
            int rs = stt.executeUpdate(sql);
            listKH.remove(i);
            myModel.removeRow(i);
            moi();
            JOptionPane.showMessageDialog(this, "Đã Xóa");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Không Thể Xóa Khách Hàng Này !");
                System.out.println(e);
            }
        }
    }
   
    public void update() {
        try {
           int row = tbl_Khachhang.getSelectedRow();
           KhachHang x = listKH.get(row);
           listKH.remove(row);
           String gioitinhKH;
           if(rdoNam_Khachhang.isSelected()) {
                    gioitinhKH = "Nam";
                }
                else{gioitinhKH = "Nữ";}
           if(check()){
                String maKH = txtMa_Khachhang.getText();
                String tenKH = txtHoTen_Khachhang.getText();
                String ngaysinhKH;
                try {
                   SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                     ngaysinhKH = sdf.format(txtNgaySinh_Khachhang.getDate());
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(this, "Chọn lại ngày sinh");
                   listKH.add(x);
                   return;
               }
                if(rdoNam_Khachhang.isSelected()) {
                    gioitinhKH = "Nam";
                }
                else{gioitinhKH = "Nữ";}
                String sdtKH = txtSoDT_Khachhang.getText();
                String cmndKH = txtCMND_Khachhang.getText();
                String emailKH = txtEmail_Khachhang.getText();
                listKH.add(row, new KhachHang(maKH, tenKH, ngaysinhKH, gioitinhKH, sdtKH, cmndKH, emailKH));
                
                String sql = "UPDATE KhachHang " +
                        "SET MaKH ='"+maKH.trim()+"',TenKH =N'"+tenKH.trim()+"',NgaySinhKH ='"+ngaysinhKH.trim()+"',GioiTinhKH =N'"+gioitinhKH.trim()+"',SDTKH ='"+sdtKH.trim()+"',CMNDKH ='"+cmndKH.trim()+"',EmailKH ='"+emailKH.trim()+"' " +
                        "WHERE MaKH ='"+maKH.trim()+"'";
                Statement stt = ketnoi.con.createStatement();
                int rs = stt.executeUpdate(sql); 
                
                myModel.setValueAt(txtMa_Khachhang.getText(), row, 0);
                myModel.setValueAt(txtHoTen_Khachhang.getText(), row, 1);
                myModel.setValueAt(ngaysinhKH, row, 2);
                myModel.setValueAt(gioitinhKH, row, 3);
                myModel.setValueAt(txtSoDT_Khachhang.getText(), row, 4);
                myModel.setValueAt(txtCMND_Khachhang.getText(), row, 5);
                myModel.setValueAt(txtEmail_Khachhang.getText(), row, 6);
                JOptionPane.showMessageDialog(this, "Đã sửa");
                tbl_Khachhang.setRowSelectionInterval(row, row);
           }
           else{
               listKH.add(row,x);
           }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void showDetail() {
        txtMa_Khachhang.setEditable(false);
        index = tbl_Khachhang.getSelectedRow();
        txtMa_Khachhang.setText((String)myModel.getValueAt(index, 0));
        txtHoTen_Khachhang.setText((String)myModel.getValueAt(index, 1));
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)myModel.getValueAt(index, 2));
            txtNgaySinh_Khachhang.setDate(date);
        } catch (Exception e) {
        }
        txtSoDT_Khachhang.setText((String)myModel.getValueAt(index, 4));
        txtCMND_Khachhang.setText((String)myModel.getValueAt(index, 5));
        txtEmail_Khachhang.setText((String)myModel.getValueAt(index, 6));
        String gt = (String)myModel.getValueAt(index, 3);
        if(gt.equals("Nam")) {
            rdoNam_Khachhang.setSelected(true);
        }
        else{
            rdoNu_Khachhang.setSelected(true);
        }
        btnSua_Khachhang.setEnabled(true);
        btnXoa_Khachhang.setEnabled(true);
        btnThem_Khachhang.setEnabled(false);
    }
    
    public void search() {
        try {
            int dem = 0;
            String maKH = JOptionPane.showInputDialog(this, "Nhập mã khách hàng cần tìm");
            for(KhachHang d : listKH) {
                if(maKH.equalsIgnoreCase(d.getMakh())) {
                    dem ++;
                    int i = listKH.indexOf(d);
                    tbl_Khachhang.setRowSelectionInterval(i, i);
                    showDetail();
                }
            }
            if(dem == 0) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy");
            }
        } catch (Exception e) {
        }
    }
}
