/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phammemquanlybatdongsan;

import Data.BatDongSan;
import Modify.BatDongSanModify;
import Modify.KetNoi;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QuanLyBatDongSan extends javax.swing.JInternalFrame {
    DefaultTableModel model;
    QuanLyBatDongSan quanLyBatDongSan;
    List<Data.BatDongSan> listBDS = new ArrayList<>();
    /**
     * Creates new form BatDongSanView
     */
    public QuanLyBatDongSan() {
        initComponents();
        model = (DefaultTableModel) tbl_BatDongSan.getModel();
        fill();
        btnSua_BatDongSan.setEnabled(false);
        btnXoa_BatDongSan.setEnabled(false);
        cboLoai_BatDongSan.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnThem_BatDongSan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSua_BatDongSan = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnXoa_BatDongSan = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnMoi_BatDongSan = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMa_BatDongSan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTen_BatDongSan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGia_BatDongSan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiaChi_BatDongSan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa_BatDongSan = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cboLoai_BatDongSan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboTrangThai_BatDongSan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_BatDongSan = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        btnThem_BatDongSan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnThem_BatDongSan.setBorderPainted(false);
        btnThem_BatDongSan.setContentAreaFilled(false);
        btnThem_BatDongSan.setFocusable(false);
        btnThem_BatDongSan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem_BatDongSan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem_BatDongSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_BatDongSanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThem_BatDongSan);
        jToolBar1.add(jSeparator1);

        btnSua_BatDongSan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua_BatDongSan.setBorderPainted(false);
        btnSua_BatDongSan.setContentAreaFilled(false);
        btnSua_BatDongSan.setFocusable(false);
        btnSua_BatDongSan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSua_BatDongSan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSua_BatDongSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_BatDongSanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSua_BatDongSan);
        jToolBar1.add(jSeparator2);

        btnXoa_BatDongSan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa_BatDongSan.setBorderPainted(false);
        btnXoa_BatDongSan.setContentAreaFilled(false);
        btnXoa_BatDongSan.setFocusable(false);
        btnXoa_BatDongSan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa_BatDongSan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa_BatDongSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_BatDongSanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnXoa_BatDongSan);
        jToolBar1.add(jSeparator3);

        btnMoi_BatDongSan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnMoi_BatDongSan.setBorderPainted(false);
        btnMoi_BatDongSan.setContentAreaFilled(false);
        btnMoi_BatDongSan.setFocusable(false);
        btnMoi_BatDongSan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMoi_BatDongSan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMoi_BatDongSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoi_BatDongSanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMoi_BatDongSan);
        jToolBar1.add(jSeparator4);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator5);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Bất Động Sản", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Mã :");

        txtMa_BatDongSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Tên :");

        txtTen_BatDongSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Giá :");

        txtGia_BatDongSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Địa Chỉ :");

        txtDiaChi_BatDongSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtMoTa_BatDongSan.setColumns(20);
        txtMoTa_BatDongSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtMoTa_BatDongSan.setRows(5);
        jScrollPane2.setViewportView(txtMoTa_BatDongSan);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Loại :");

        cboLoai_BatDongSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cboLoai_BatDongSan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đất nền", "Biệt thự", "Căn Hộ" }));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Mô Tả :");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Trạng Thái :");

        cboTrangThai_BatDongSan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cboTrangThai_BatDongSan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa bán", "Đã bán" }));
        cboTrangThai_BatDongSan.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtGia_BatDongSan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTen_BatDongSan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMa_BatDongSan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiaChi_BatDongSan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboLoai_BatDongSan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTrangThai_BatDongSan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(134, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMa_BatDongSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboLoai_BatDongSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTrangThai_BatDongSan, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(txtTen_BatDongSan))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(txtGia_BatDongSan))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(txtDiaChi_BatDongSan))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tbl_BatDongSan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã BDS", "Tên BDS", "Giá", "Đại chỉ", "Loại", "Mô tả", "Trạng thái"
            }
        ));
        tbl_BatDongSan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BatDongSanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_BatDongSan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_BatDongSanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_BatDongSanMouseClicked
        // TODO add your handling code here:
        showDetail();
    }//GEN-LAST:event_tbl_BatDongSanMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnMoi_BatDongSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoi_BatDongSanActionPerformed
        // TODO add your handling code here:
        moi();
    }//GEN-LAST:event_btnMoi_BatDongSanActionPerformed

    private void btnXoa_BatDongSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_BatDongSanActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoa_BatDongSanActionPerformed

    private void btnSua_BatDongSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_BatDongSanActionPerformed
        // TODO add your handling code here:
        sua();
    }//GEN-LAST:event_btnSua_BatDongSanActionPerformed

    private void btnThem_BatDongSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_BatDongSanActionPerformed
        // TODO add your handling code here:
        them();
    }//GEN-LAST:event_btnThem_BatDongSanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi_BatDongSan;
    private javax.swing.JButton btnSua_BatDongSan;
    private javax.swing.JButton btnThem_BatDongSan;
    private javax.swing.JButton btnXoa_BatDongSan;
    private javax.swing.JComboBox<String> cboLoai_BatDongSan;
    private javax.swing.JComboBox<String> cboTrangThai_BatDongSan;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbl_BatDongSan;
    private javax.swing.JTextField txtDiaChi_BatDongSan;
    private javax.swing.JTextField txtGia_BatDongSan;
    private javax.swing.JTextField txtMa_BatDongSan;
    private javax.swing.JTextArea txtMoTa_BatDongSan;
    private javax.swing.JTextField txtTen_BatDongSan;
    // End of variables declaration//GEN-END:variables

        private void fill() {
        listBDS = Modify.BatDongSanModify.filltoTable();
        model.setRowCount(0);
        listBDS.forEach((bdse) -> {
            model.addRow(new Object[]{bdse.getMa(), bdse.getTen(), bdse.getGia(), bdse.getDiachi(), bdse.getLoai(), bdse.getMota(), bdse.getTrangthai()});
        });
    }

    public void openBatDongSan() {
        quanLyBatDongSan = new QuanLyBatDongSan();
        quanLyBatDongSan.setVisible(true);
    }

    public void moi() {
        txtMa_BatDongSan.setText("");
        txtTen_BatDongSan.setText("");
        txtGia_BatDongSan.setText("");
        txtDiaChi_BatDongSan.setText("");
        cboLoai_BatDongSan.setSelectedIndex(0);
        txtMoTa_BatDongSan.setText("");
        cboTrangThai_BatDongSan.setSelectedIndex(0);
        txtMa_BatDongSan.setEditable(true);
        btnThem_BatDongSan.setEnabled(true);
        btnSua_BatDongSan.setEnabled(false);
        btnXoa_BatDongSan.setEnabled(false);
        cboLoai_BatDongSan.setSelectedIndex(0);
    }

    public boolean check() {

        if (txtMa_BatDongSan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap Ma");
            txtMa_BatDongSan.requestFocus();
            return false;
        }
        if (txtTen_BatDongSan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap ten");
            txtTen_BatDongSan.requestFocus();
            return false;
        }
        if (txtGia_BatDongSan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap gia");
            txtGia_BatDongSan.requestFocus();
            return false;
        }
        if (txtGia_BatDongSan.getText().length() > 17) {
            JOptionPane.showMessageDialog(this, "Gia BDS qua cao");
            txtGia_BatDongSan.setText("");
            txtGia_BatDongSan.requestFocus();
            return false;
        }
        try {
            Double.parseDouble(txtGia_BatDongSan.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Gia khong dung dinh dang");
            txtGia_BatDongSan.setText("");
            txtGia_BatDongSan.requestFocus();
            return false;
        }
        if (txtDiaChi_BatDongSan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap dia chi");
            txtDiaChi_BatDongSan.requestFocus();
            return false;
        }
        if (txtMoTa_BatDongSan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap mo ta");
            txtMoTa_BatDongSan.requestFocus();
            return false;
        }
        return true;
    }

    public boolean checkDup() {
        for (int i = 0; i < listBDS.size(); i++) {
            if (txtMa_BatDongSan.getText().equalsIgnoreCase(listBDS.get(i).getMa())) {
                JOptionPane.showMessageDialog(this, "Ma BDS da duoc su dung");
                txtMa_BatDongSan.setText("");
                txtMa_BatDongSan.requestFocus();
                return false;
            }
        }
        return true;
    }

    public void them() {
        if (check() && checkDup()) {
            try {
                BatDongSan batDongSan = new BatDongSan(txtMa_BatDongSan.getText(),
                        txtTen_BatDongSan.getText(),
                        txtGia_BatDongSan.getText(),
                        txtDiaChi_BatDongSan.getText(),
                        cboLoai_BatDongSan.getSelectedItem().toString(),
                        txtMoTa_BatDongSan.getText(),
                        cboTrangThai_BatDongSan.getSelectedItem().toString());
                listBDS.add(batDongSan);
                Modify.BatDongSanModify.insert(batDongSan);
                fill();
                JOptionPane.showMessageDialog(this, "Da them BDS");
            } catch (HeadlessException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }

    public void showDetail() {
        int i = tbl_BatDongSan.getSelectedRow();
        if (i >= 0) {
            Data.BatDongSan bds = listBDS.get(i);
            txtMa_BatDongSan.setText(bds.getMa());
            txtTen_BatDongSan.setText(bds.getTen());
            txtGia_BatDongSan.setText(String.valueOf(bds.getGia()));
            txtDiaChi_BatDongSan.setText(bds.getDiachi());
            cboLoai_BatDongSan.setSelectedItem(bds.getLoai());
            txtMoTa_BatDongSan.setText(bds.getMota());
            cboTrangThai_BatDongSan.setSelectedItem(bds.getTrangthai());
            txtMa_BatDongSan.setEditable(false);
            btnThem_BatDongSan.setEnabled(false);
            btnSua_BatDongSan.setEnabled(true);
            btnXoa_BatDongSan.setEnabled(true);
        }
    }

    public void xoa() {
        int a = listBDS.size();
        int i = tbl_BatDongSan.getSelectedRow();
        if (i >= 0) {
            String ma = listBDS.get(i).getMa();
//            try {
                BatDongSanModify.delete(ma);
                if (!BatDongSanModify.delete(ma)) {
                    JOptionPane.showMessageDialog(this, "Bat dong san nay dang duoc su dung");
                    tbl_BatDongSan.setRowSelectionInterval(i, i);
                } else{
                    listBDS.remove(i);
                    System.out.println(a);
                    System.out.println(listBDS.size());
                    fill();
                    moi();
                    JOptionPane.showMessageDialog(this, "Da xoa BDS");
                }
//            } catch (HeadlessException e) {
//                JOptionPane.showMessageDialog(this, e);
//            }
        } else {
            JOptionPane.showMessageDialog(this, "Chon BDS can xoa");
        }
    }
    KetNoi ketnoi;

    public void sua() {
        int i = tbl_BatDongSan.getSelectedRow();
        if (i >= 0) {
            BatDongSan batDongSan = listBDS.get(i);
            String ma = batDongSan.getMa();
            if (check()) {
                batDongSan.setTen(txtTen_BatDongSan.getText());
                batDongSan.setGia(txtGia_BatDongSan.getText());
                batDongSan.setDiachi(txtDiaChi_BatDongSan.getText());
                batDongSan.setLoai((String) cboLoai_BatDongSan.getSelectedItem());
                batDongSan.setMota(txtMoTa_BatDongSan.getText());
                batDongSan.setTrangthai((String) cboTrangThai_BatDongSan.getSelectedItem());
                BatDongSanModify.update(batDongSan, ma);
                fill();
                JOptionPane.showMessageDialog(this, "Da cap nhat du lieu");
                tbl_BatDongSan.setRowSelectionInterval(i, i);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chon BDS can sua");
        }
    }
    public void search() {
        try {
            int dem = 0;
            String mabds = JOptionPane.showInputDialog(this, "Nhập mã bất động sản cần tìm");
            for(BatDongSan d : listBDS) {
                if(mabds.equalsIgnoreCase(d.getMa())) {
                    dem ++;
                    int i = listBDS.indexOf(d);
                    tbl_BatDongSan.setRowSelectionInterval(i, i);
                    showDetail();
                }
            }
            if(dem == 0) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy");
            }
        } catch (Exception e) {
        }
    }
}
