/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phammemquanlybatdongsan;
import Data.BatDongSan;
import Data.HopDong;
import Data.KhachHang;
import Data.NhanVien;
import Modify.HopDongModify;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author admin
 */
public class QuanLyHopDong extends javax.swing.JInternalFrame {

    QuanLyNhanVien qlnv;
    QuanLyKhachHang qlkh;
    QuanLyBatDongSan qlbds;

    DefaultTableModel model;
    QuanLyHopDong quanLyHopDong;
    List<Data.HopDong> listHD = new ArrayList<>();
    Date date = null;

    /**
     * Creates new form HopDongView
     */
    public QuanLyHopDong() {
        initComponents();
        model = (DefaultTableModel) tbl_HopDong.getModel();
        fill();
        btnSua_HopDong.setEnabled(false);
        btnXoa_HopDong.setEnabled(false);
        txtNgayTao_HopDong.setText(String.valueOf(java.time.LocalDate.now()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        btnThem_HopDong = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnSua_HopDong = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnXoa_HopDong = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnMoi_HopDong = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaHD_HopDong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenHD_HopDong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV_HopDong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNgayTao_HopDong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMaBDS_HopDong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaKH_HopDong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HopDong = new javax.swing.JTable();

        jToolBar2.setRollover(true);

        btnThem_HopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnThem_HopDong.setBorderPainted(false);
        btnThem_HopDong.setContentAreaFilled(false);
        btnThem_HopDong.setFocusable(false);
        btnThem_HopDong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem_HopDong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem_HopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_HopDongActionPerformed(evt);
            }
        });
        jToolBar2.add(btnThem_HopDong);
        jToolBar2.add(jSeparator4);

        btnSua_HopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua_HopDong.setBorderPainted(false);
        btnSua_HopDong.setContentAreaFilled(false);
        btnSua_HopDong.setFocusable(false);
        btnSua_HopDong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSua_HopDong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSua_HopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_HopDongActionPerformed(evt);
            }
        });
        jToolBar2.add(btnSua_HopDong);
        jToolBar2.add(jSeparator5);

        btnXoa_HopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoa_HopDong.setBorderPainted(false);
        btnXoa_HopDong.setContentAreaFilled(false);
        btnXoa_HopDong.setFocusable(false);
        btnXoa_HopDong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa_HopDong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa_HopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_HopDongActionPerformed(evt);
            }
        });
        jToolBar2.add(btnXoa_HopDong);
        jToolBar2.add(jSeparator3);

        btnMoi_HopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnMoi_HopDong.setBorderPainted(false);
        btnMoi_HopDong.setContentAreaFilled(false);
        btnMoi_HopDong.setFocusable(false);
        btnMoi_HopDong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMoi_HopDong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMoi_HopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoi_HopDongActionPerformed(evt);
            }
        });
        jToolBar2.add(btnMoi_HopDong);
        jToolBar2.add(jSeparator6);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);
        jToolBar2.add(jSeparator1);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton8);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Hợp Đồng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Mã HĐ :");

        txtMaHD_HopDong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Tên HĐ :");

        txtTenHD_HopDong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Mã NV :");

        txtMaNV_HopDong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Ngày Tạo :");

        txtNgayTao_HopDong.setEditable(false);
        txtNgayTao_HopDong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Mã BĐS :");

        txtMaBDS_HopDong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Mã KH :");

        txtMaKH_HopDong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaHD_HopDong, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtTenHD_HopDong)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(txtMaNV_HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMaKH_HopDong)
                        .addComponent(txtMaBDS_HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNgayTao_HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaKH_HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaBDS_HopDong))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNgayTao_HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaHD_HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenHD_HopDong))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV_HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        tbl_HopDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HĐ", "Tên HĐ", "Mã NV", "Mã KH", "Mã BĐS", "Ngày Tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_HopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HopDongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_HopDong);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoa_HopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_HopDongActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoa_HopDongActionPerformed

    private void btnMoi_HopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoi_HopDongActionPerformed
        // TODO add your handling code here:
        moi();
    }//GEN-LAST:event_btnMoi_HopDongActionPerformed

    private void btnSua_HopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_HopDongActionPerformed
        // TODO add your handling code here:
        sua();
    }//GEN-LAST:event_btnSua_HopDongActionPerformed

    private void btnThem_HopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_HopDongActionPerformed
        // TODO add your handling code here:
        them();
    }//GEN-LAST:event_btnThem_HopDongActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tbl_HopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HopDongMouseClicked
        // TODO add your handling code here:
        showDetail();
    }//GEN-LAST:event_tbl_HopDongMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi_HopDong;
    private javax.swing.JButton btnSua_HopDong;
    private javax.swing.JButton btnThem_HopDong;
    private javax.swing.JButton btnXoa_HopDong;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTable tbl_HopDong;
    private javax.swing.JTextField txtMaBDS_HopDong;
    private javax.swing.JTextField txtMaHD_HopDong;
    private javax.swing.JTextField txtMaKH_HopDong;
    private javax.swing.JTextField txtMaNV_HopDong;
    private javax.swing.JTextField txtNgayTao_HopDong;
    private javax.swing.JTextField txtTenHD_HopDong;
    // End of variables declaration//GEN-END:variables
    private void fill() {
        listHD = Modify.HopDongModify.filltoTable();
        model.setRowCount(0);
        listHD.forEach((hds) -> {
            model.addRow(new Object[]{hds.getMa(), hds.getTen(), hds.getManv(), hds.getMakh(), hds.getMabds(), hds.getNgaytao()});
        });
    }

    public void moi() {
        txtMaHD_HopDong.setText("");
        txtTenHD_HopDong.setText("");
        txtMaNV_HopDong.setText("");
        txtMaKH_HopDong.setText("");
        txtMaBDS_HopDong.setText("");
        txtNgayTao_HopDong.setText("");
        txtMaHD_HopDong.setEditable(true);
        txtMaBDS_HopDong.setEditable(true);
        btnThem_HopDong.setEnabled(true);
        btnXoa_HopDong.setEnabled(false);
        btnSua_HopDong.setEnabled(false);
        txtNgayTao_HopDong.setText(String.valueOf(java.time.LocalDate.now()));
    }

    public boolean check() {

        qlnv = new QuanLyNhanVien();
        ArrayList<NhanVien> listNV = qlnv.list_NhanVien;

        qlkh = new QuanLyKhachHang();
        ArrayList<KhachHang> listKH = qlkh.listKH;

        qlbds = new QuanLyBatDongSan();
        List<BatDongSan> listBDS = qlbds.listBDS;

        if (txtMaHD_HopDong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap ma hop dong");
            txtMaHD_HopDong.requestFocus();
            return false;
        }
        if (txtTenHD_HopDong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap ten hop dong");
            txtTenHD_HopDong.requestFocus();
            return false;
        }
        if (txtMaNV_HopDong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap ma nhan vien");
            txtMaNV_HopDong.requestFocus();
            return false;
        }
        int a = 0;
        for (int i = 0; i < listNV.size(); i++) {
            if (listNV.get(i).getMa().equalsIgnoreCase(txtMaNV_HopDong.getText())) {
                a++;
            }
        }
        if (a == 0) {
            JOptionPane.showMessageDialog(qlnv, "Ma nhan vien khong ton tai");
            System.out.println(listNV.size());
            txtMaNV_HopDong.setText("");
            txtMaNV_HopDong.requestFocus();
            return false;
        }
        if (txtMaKH_HopDong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap ma khach hang");
            txtMaKH_HopDong.requestFocus();
            return false;
        }
        int b = 0;
        for (int i = 0; i < listKH.size(); i++) {
            if (listKH.get(i).getMakh().equalsIgnoreCase(txtMaKH_HopDong.getText())) {
                b++;
            }
        }
        if (b == 0) {
            JOptionPane.showMessageDialog(qlkh, "Ma khach hang khong ton tai");
            txtMaKH_HopDong.setText("");
            txtMaKH_HopDong.requestFocus();
            return false;
        }
        if (txtMaBDS_HopDong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap ma bat dong san");
            txtMaBDS_HopDong.requestFocus();
            return false;
        }
        int c = 0;
        for (int i = 0; i < listBDS.size(); i++) {
            if (listBDS.get(i).getMa().equalsIgnoreCase(txtMaBDS_HopDong.getText())) {
                c++;
            }
        }
        if (c == 0) {
            JOptionPane.showMessageDialog(qlbds, "Ma bat dong san khong ton tai");
            txtMaBDS_HopDong.setText("");
            txtMaBDS_HopDong.requestFocus();
            return false;
        }
        if (txtNgayTao_HopDong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap ngay tao hop dong");
            txtNgayTao_HopDong.requestFocus();
            return false;
        }
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(txtNgayTao_HopDong.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Loi ngay tao hop dong");
            txtNgayTao_HopDong.setText("");
            txtNgayTao_HopDong.requestFocus();
            return false;
        }

        return true;
    }

    public boolean checkDup() {
        for (int i = 0; i < tbl_HopDong.getRowCount(); i++) {
            String ma = (String) tbl_HopDong.getValueAt(i, 0);
            if (txtMaHD_HopDong.getText().equals(ma)) {
                JOptionPane.showMessageDialog(this, "Ma hop dong da duoc su dung");
                txtMaHD_HopDong.requestFocus();
                txtMaHD_HopDong.setText("");
                return false;
            }
        }

        for (int i = 0; i < tbl_HopDong.getRowCount(); i++) {
            String ma = (String) tbl_HopDong.getValueAt(i, 4);
            if (txtMaBDS_HopDong.getText().equals(ma)) {
                JOptionPane.showMessageDialog(this, "bat dong san nay da duoc ban");
                txtMaBDS_HopDong.requestFocus();
                txtMaBDS_HopDong.setText("");
                return false;
            }
        }

        return true;
    }

    public boolean checkNull() {

        qlnv = new QuanLyNhanVien();
        ArrayList<NhanVien> listNV = qlnv.list_NhanVien;

        qlkh = new QuanLyKhachHang();
        ArrayList<KhachHang> listKH = qlkh.listKH;

        qlbds = new QuanLyBatDongSan();
        List<BatDongSan> listBDS = qlbds.listBDS;

        int a = 0;
        for (int i = 0; i < listNV.size(); i++) {
            if (listNV.get(i).getMa().equalsIgnoreCase(txtMaNV_HopDong.getText())) {
                a++;
            }
        }
        if (a == 0) {
            JOptionPane.showMessageDialog(qlnv, "Ma nhan vien khong ton tai");
            System.out.println(listNV.size());
            txtMaNV_HopDong.setText("");
            txtMaNV_HopDong.requestFocus();
            return false;
        }
        int b = 0;
        for (int i = 0; i < listKH.size(); i++) {
            if (listKH.get(i).getMakh().equalsIgnoreCase(txtMaKH_HopDong.getText())) {
                b++;
            }
        }
        if (b == 0) {
            JOptionPane.showMessageDialog(qlkh, "Ma khach hang khong ton tai");
            txtMaKH_HopDong.setText("");
            txtMaKH_HopDong.requestFocus();
            return false;
        }
        int c = 0;
        for (int i = 0; i < listBDS.size(); i++) {
            if (listBDS.get(i).getMa().equalsIgnoreCase(txtMaBDS_HopDong.getText())) {
                c++;
            }
        }
        if (c == 0) {
            JOptionPane.showMessageDialog(qlbds, "Ma bat dong san khong ton tai");
            txtMaBDS_HopDong.setText("");
            txtMaBDS_HopDong.requestFocus();
            return false;
        }

        return true;
    }

    public void them() {
        int i = listHD.size();
        if (check() && checkDup() && checkNull()) {
            try {
                
                Data.HopDong hopDong = new Data.HopDong(txtMaHD_HopDong.getText(),
                        txtTenHD_HopDong.getText(),
                        txtMaNV_HopDong.getText(),
                        txtMaKH_HopDong.getText(),
                        txtMaBDS_HopDong.getText(),
                        txtNgayTao_HopDong.getText());
                listHD.add(hopDong);
                Modify.HopDongModify.insert(hopDong);
                fill();
                if (listHD.size() > i) {
                    JOptionPane.showMessageDialog(qlnv, "Da them hop dong");
                } else {
                    JOptionPane.showMessageDialog(this, "Loi ngay tao hop dong");
                    txtNgayTao_HopDong.setText("");
                    txtNgayTao_HopDong.requestFocus();
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }

    public void showDetail() {
        int i = tbl_HopDong.getSelectedRow();
        if (i >= 0) {
            Data.HopDong hd = listHD.get(i);
            txtMaHD_HopDong.setText(hd.getMa());
            txtTenHD_HopDong.setText(hd.getTen());
            txtMaNV_HopDong.setText(hd.getManv());
            txtMaKH_HopDong.setText(hd.getMakh());
            txtMaBDS_HopDong.setText(hd.getMabds());
            txtNgayTao_HopDong.setText(hd.getNgaytao());
            txtMaHD_HopDong.setEditable(false);
            txtMaBDS_HopDong.setEditable(false);
            btnThem_HopDong.setEnabled(false);
            btnSua_HopDong.setEnabled(true);
            btnXoa_HopDong.setEnabled(true);
        }
    }

    public void xoa() {
        int i = tbl_HopDong.getSelectedRow();
        if (i >= 0) {
            String ma = listHD.get(i).getMa();
            try {
                HopDongModify.delete(ma);
                fill();
                moi();
                JOptionPane.showMessageDialog(this, "Da Xoa Hop Dong");
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chon hop dong can xoa");
        }
    }

    public void sua() {
        int i = tbl_HopDong.getSelectedRow();
        HopDong hopDong1 = listHD.get(i);
        String temp = hopDong1.getTen() + hopDong1.getManv() + hopDong1.getMakh() + hopDong1.getNgaytao();
        if (i >= 0) {
            HopDong hopDong = listHD.get(i);
            String ma = hopDong.getMa();
            if (check()) {
                hopDong.setTen(txtTenHD_HopDong.getText());
                hopDong.setManv(txtMaNV_HopDong.getText());
                hopDong.setMakh(txtMaKH_HopDong.getText());
                txtNgayTao_HopDong.setText(String.valueOf(java.time.LocalDate.now()));
                hopDong.setNgaytao(txtNgayTao_HopDong.getText());
                String temp1 = hopDong.getTen() + hopDong.getManv() + hopDong.getMakh() + hopDong.getNgaytao();
                HopDongModify.update(hopDong, ma);
                fill();
                System.out.println(temp + "\n" + temp1);
                if (!temp.equals(temp1)) {
                    JOptionPane.showMessageDialog(this, "Da cap nhat du lieu");
                } else if (temp.equals(temp1)) {
                    JOptionPane.showMessageDialog(this, "Hop dong khong bi thay doi");
                } else {
                    JOptionPane.showMessageDialog(this, "Loi ngay tao hop dong");
                    txtNgayTao_HopDong.setText("");
                    txtNgayTao_HopDong.requestFocus();
                }
                tbl_HopDong.setRowSelectionInterval(i, i);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chon Hop dong can sua");
        }
    }
    public void search() {
        try {
            int dem = 0;
            String maHD = JOptionPane.showInputDialog(this, "Nhập mã hợp đồng tìm");
            for(HopDong d : listHD) {
                if(maHD.equalsIgnoreCase(d.getMa())) {
                    dem ++;
                    int i = listHD.indexOf(d);
                    tbl_HopDong.setRowSelectionInterval(i, i);
                    showDetail();
                }
            }
            if(dem == 0) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy");
            }
        } catch (Exception e) {
        }
    }
}
